name: 'Setup Python Environment'
description: 'Setup Python with development dependencies'

inputs:
  python-version:
    description: 'Python version to use'
    required: true
    default: '3.10'

runs:
  using: 'composite'
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt', '**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install system dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          build-essential \
          libffi-dev \
          libssl-dev \
          python3-dev
      if: runner.os == 'Linux'

    - name: Install Python dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip setuptools wheel
        # Install torch with CPU-specific index for CI performance
        python -m pip install torch==2.8.0 torchvision --index-url https://download.pytorch.org/whl/cpu
        # Install development dependencies
        python -m pip install -e ".[test,dev]"
        # Install pre-commit hooks
        pre-commit install-hooks

    - name: Check Python version
      shell: bash
      run: python --version && pip --version
